---
- name: Cria link simbólico home --> /web/shared/home/{{ servico | trim }}
  ansible.builtin.file:
    src: /web/shared/home/{{ servico | trim }}
    dest: /web/shared/servers/{{ servico | trim }}/home
    state: link

- name: Cria link simbólico httpd --> /usr/sbin/httpd
  ansible.builtin.file:
    src: /usr/sbin/httpd
    dest: /web/shared/servers/{{ servico | trim }}/httpd
    state: link 

- name: Cria link simbólico modules --> /usr/lib64/httpd/modules
  ansible.builtin.file:
    src: /usr/lib64/httpd/modules
    dest: /web/shared/servers/{{ servico | trim }}/modules
    state: link

- name: Cria link simbólico pid --> /run/httpd
  ansible.builtin.file:
    src: /run/httpd
    dest: /web/shared/servers/{{ servico | trim }}/pids
    state: link

- name: Cria link simbólico mod_wsgi.so --> /usr/lib64/httpd/modules/mod_wsgi_python3.so
  ansible.builtin.file:
    src: /usr/lib64/httpd/modules/mod_wsgi_python3.so
    dest: /usr/lib64/httpd/modules/mod_wsgi.so
    state: link

- name: Força owner/group do link home como {{ usuario }}
  ansible.builtin.command: chown -h {{ usuario }}:{{ grupo }} {{ item }}
  loop:
    - /web/shared/servers/{{ servico | trim }}/httpd
    - /web/shared/servers/{{ servico | trim }}/modules
    - /web/shared/servers/{{ servico | trim }}/pids
    - /web/shared/servers/{{ servico | trim }}/home
  changed_when: false

- name: Transferir arquivos bin para diretório
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /web/shared/servers/{{ servico | trim }}/bin
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
    mode: "0774"
  loop:
    - checkHttpConfig.sh
    - menu.sh

- name: Transferir arquivos para diretório de configuração
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /web/shared/servers/{{ servico | trim }}/bin/setHttpEnv.sh
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
    mode: "0774"
  loop:
    - setHttpEnv.j2

- name: Transferir arquivos para diretório de serviço
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /web/shared/servers/{{ servico | trim }}
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
    mode: "0774"
  loop:
    - restart_graceful
    - restart_now
    - start
    - stop_graceful
    - stop_now
  
- name: Transferir arquivos para diretório de configuração
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /web/shared/servers/{{ servico | trim }}/conf/httpd.conf
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
    mode: "0664"
  loop:
    - httpd.j2

- name: Transferir arquivos para diretório de configuração
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /web/shared/servers/{{ servico | trim }}/conf/applications.d
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
    mode: "0664"
  loop:
    - welcome.cfg

- name: Transferir arquivos para diretório de configuração
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /web/shared/servers/{{ servico | trim }}/conf/modules.d
    owner: "{{ usuario }}"
    group: "{{ grupo }}"
    mode: "0664"
  loop:
    - 00-base.conf
    - 00-dav.conf
    - 00-ssl.conf
    - 00-systemd.conf
    - 01-proxy.conf