#!/bin/bash

scriptDir=dirname "$0"

#Configura variaveis de ambiente
. ${scriptDir}/bin/setHttpEnv.sh


# RESTART GRACEFUL - SIGNAL: USR1
ps --ppid cat ${HTTP_PID_FILE} -o pid h > ${HTTP_CHECKRESTART_PID_FILE}
kill -USR1 cat ${HTTP_PID_FILE}