---
- name: "Instalar e compilar Jansson"
  ansible.builtin.shell: |
    git clone https://github.com/akheron/jansson.git && \
    cd jansson && \
    autoreconf -i && \
    ./configure --prefix=/usr --libdir=/usr/lib64 && \
    make && \
    make install
  args:
    creates: /usr/lib64/libjansson.so

- name: "Baixar Asterisk via curl"
  ansible.builtin.shell: |
    curl -L -o asterisk-20.15.2.tar.gz https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-20.15.2.tar.gz
  args:
    chdir: /usr/src
    creates: /usr/src/asterisk-20.15.2.tar.gz

- name: "Extrair Asterisk"
  ansible.builtin.shell: |
    tar -zxvf asterisk-20.15.2.tar.gz
  args:
    chdir: /usr/src
    creates: /usr/src/asterisk-20.15.2

- name: "Instalar e compilar Asterisk"
  ansible.builtin.shell: |
    ./contrib/scripts/install_prereq install && \
    ./configure --libdir=/usr/lib64 --with-jansson-bundled && \
    make && \
    make install && \
    make samples && \
    make config && \
    make install-logrotate
  args:
    chdir: /usr/src/asterisk-20.15.2
    creates: /usr/sbin/asterisk

- name: "Copiar arquivos e modulo base do asterisk"
  ansible.builtin.copy:
    src: odbc.ini
    dest: /etc/odbc.ini
    owner: root
    group: root

- name: "Copiar arquivos e modulo base do asterisk"
  ansible.builtin.copy:
    src: psqlodbcw.so
    dest: /usr/lib64
    owner: root
    group: root
    mode: '0554'

- name: "Copiar arquivos e modulo base do asterisk"
  ansible.builtin.copy:
    src: etc-asterisk-padrao.tar.gz
    dest: /tmp/etc-asterisk-padrao.tar.gz
  
- name: "Copiar arquivos e modulo base do asterisk"
  ansible.builtin.copy:
    src: var-config-asterisk20.tar.gz
    dest: /tmp/var-config-asterisk20.tar.gz

- name: "Instalar arquivos base do asterisk"
  ansible.builtin.shell: |
    rm -rf /etc/asterisk/* && \
    etc-asterisk-padrao.tar.gz /etc/asterisk && \
    tar -zxvf /etc/asterisk/etc-asterisk-padrao.tar.gz -C /etc/asterisk && rm -rf /etc/asterisk/etc-asterisk-padrao.tar.gz && \
    rm -rf /tmp/var-config-asterisk20.tar.gz && rm -rf /tmp/etc-asterisk-padrao.tar.gz 
  args:
    chdir: /tmp

- name: "Ajustar permissão do asterisk"
  ansible.builtin.shell: |
    chown -R asterisk:asterisk \
    /etc/asterisk \
    /var/{lib,log,spool,run,cache}/asterisk \
    /usr/lib64/asterisk